CREATE TABLE IF NOT EXISTS `inventory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `house_id` INT UNSIGNED NOT NULL, 
  `type_id` INT UNSIGNED NOT NULL,
  `count` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE, 
  CONSTRAINT `inventory_house_id_fk` FOREIGN KEY (`house_id`)
  REFERENCES `house`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `type_id_fk` FOREIGN KEY (`type_id`)
  REFERENCES `inventory_type`(`id`) ON UPDATE CASCADE ON DELETE CASCADE);

