INSERT INTO `association` (`name`, `building_id`) VALUES (' Центр экологических инициатив', 1);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Изо-студия Штрих', 16);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Лига КВН Деревни Универсиады', 14);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Клуб настольных игр Пандорика', 7);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Клуб рукоделия Острые иголочки', 6);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Клуб интеллектуальных игр ДУМ)', 3);
INSERT INTO `association` (`name`, `building_id`) VALUES ('(FreeDOM', 26);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Театральная студия Бесконечность', 38);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Международный клуб', 18);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Клуб рукоделия Острые иголочки', 37);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Клуб интеллектуальных игр ДУМ)', 38);
INSERT INTO `association` (`name`, `building_id`) VALUES (' Клуб рукоделия Острые иголочки', 21);