INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Своя Игра', 4, 1);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Хеллоуин 2020', 34, 3);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Стритбол', 23, 1);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Quiz', 37, 1);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Киновечер', 18, 3);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('SWAP PARTY', 26, 5);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('WorkOut', 27, 2);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Гитарник', 32, 4);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Тайный друг', 25, 5);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Bring Sally Up', 20, 4);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Like a Donor', 13, 5);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Кухня народов мира', 29, 4);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('Тайный Санта', 15, 2);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('ЛИМБО', 12, 1);
INSERT INTO `event` (`name`, `address_id`, `mark`) VALUES ('ЧГК', 39, 5);